services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - POSTGRES_DB=ragchat
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
