services:
  app:
    #build:
    #context: ./   #builds the docker image from Dockerfile in current directory
    #dockerfile: Dockerfile
    image: spring-ai-samples-vaadin
    env_file:
      .env
    environment:
      - OPENAI_API_KEY
      - DB_USER
      - DB_PASSWORD
      - SERVER_SERVLET_CONTEXT_PATH=/chatwithdocs
      #- OLLAMA_URL=http://ollama:11434
    ports:
      - "28861:8080"
    depends_on:
      - pgvector
      #- ollama
    networks:
      - app-network
    #restart: always


  pgvector:
    image: 'pgvector/pgvector:pg16'
    env_file:
      .env
    environment:
      - POSTGRES_DB=ragchat
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432'
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
    #restart: always

  #ollama:
  #  image: alpine/ollama:latest
  #  ports:
  #    - '11434'
  #  networks:
  #    - app-network
  #  volumes:
  #    - ollama:/root/.ollama

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  #ollama: